cas:
  build: ../auth/cas41
  volumes:
    - ./authentication.txt:/etc/cas/authentication.txt
    - ./cas.properties:/etc/cas/cas.properties
  ports:
    - 9001:8080

# /etc/hosts
# `docker-machine ip default` sso.triangle.edu
